version: '3'

networks: 
  laravel:

services: 
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - laravel
  php:
    build: 
      context: ./docker/php
      dockerfile: dockerfile
    container_name: php
    volumes: 
      - ./:/var/www/html
    ports: 
      - '9000:9000'
    networks: 
      - laravel
  composer:
    image: composer
    working_dir: /var/www/html
    volumes: 
      - ./:/var/www/html
    networks: 
      - laravel
    container_name: composer
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - '3306:3306'
    volumes: 
      - ./docker/mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: laravel
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICES_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - laravel
    